# 应用服务 WEB 访问端口
server:
  port: 8002
  servlet:
    context-path: /business
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      time-to-live: 60s
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.jiawa.train.business.mapper: trace